# Generated by Django 3.0 on 2025-07-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'adresse', 'verbose_name_plural': 'adresses'},
        ),
    ]
